# Generated by Django 3.0.5 on 2022-04-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50)),
                ('faculty_name', models.CharField(default=None, max_length=100)),
                ('date', models.DateField(default=None)),
                ('time', models.CharField(default=None, max_length=10)),
                ('fees', models.FloatField(default=None)),
                ('duration', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Model',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Enrolled_Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default=None, max_length=50)),
                ('faculty_name', models.CharField(default=None, max_length=100)),
                ('date', models.DateField(default=None)),
                ('time', models.CharField(default=None, max_length=10)),
                ('fees', models.FloatField(default=None)),
                ('duration', models.IntegerField(default=None)),
                ('student_id', models.ManyToManyField(to='app27.Student_Model')),
            ],
        ),
    ]
